version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/travel-app-cicd/
permissions:
  - object: /home/ec2-user/travel-app-cicd/
    owner: ec2-user
    mode: 777
hooks:
  AfterInstall:
    - location: /home/ec2-user/travel-app-cicd/setup.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    # - location: run.sh
    #   timeout: 300
    #   runas: root
