version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/travel-app-cicd/
permissions:
  - object: /home/ec2-user/travel-app-cicd/
    owner: ec2-user
    mode: 777
hooks:
  # AfterInstall:
  #   - location: run.sh
  #     timeout: 3000
  #     runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
