version: "2.4"
services: 
  frontend:
    image: hjy/docker_front
    build: 
      context: ./front
      dockerfile: Dockerfile.dev
    # volumes:
    #   - /app/node_modules
    #   - ./front:/app
    # stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    mem_limit: 128m
  nginx:
    restart: always # nginx는 소중하니깐
    image: hjy/docker_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend
  backend:
    image: hjy/docker_back
    build: 
      context: ./back
      dockerfile: Dockerfile
    container_name: app_backend
    volumes:
      - ./back:/app
    mem_limit: 128m



