version: "3"
services: 
  nuxt:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # volumes:
    #   - /app/node_modules
    #   - ./:/app
    # stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  # tests:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /usr/src/app/node_modules
  #     - ./:/usr/src/app
    # command: ["npm", "run", "test"]



