FROM node:alpine

WORKDIR /app

COPY package.json ./

RUN npm install

COPY ./ ./

CMD ["npm", "run", "dev"]

ENV CHOKIDAR_USEPOLLING=true

#set app serving to permissive / assigned
ENV HOST 0.0.0.0

#expose 3000 on container
EXPOSE 3000

