name: Docker CI/CD Pipeline

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

    - name: Login to dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker Dev Front
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker_front -f ./front/Dockerfile.dev ./front
    
#     - name: Run Test
#       run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/docker_front npm run test -- --coverage
    
    - name: Build Docker Front image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker_front ./front
    - name: Build Docker Back image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker_back ./back
    - name: Build Docker Nginx image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker_nginx ./nginx
    - name: Push Docker Front image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/docker_front
    - name: Push Docker Back image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/docker_back
    - name: Push Docker Nginx image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/docker_nginx
          
        
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name Git_Application \
            --deployment-group-name development_gropup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
